export const DELAY_BEFORE_BEGINNING_IN_SECONDS = 1;
export const FORECAST_DURATION_IN_SECONDS = 6;
export const MORNING_TEMPERATURE_DURATION_IN_SECONDS = 6;
export const AFTERNOON_TEMPERATURE_DURATION_IN_SECONDS = 6;

export const TOTAL_DURATION =
    DELAY_BEFORE_BEGINNING_IN_SECONDS +
    MORNING_TEMPERATURE_DURATION_IN_SECONDS +
    AFTERNOON_TEMPERATURE_DURATION_IN_SECONDS +
    FORECAST_DURATION_IN_SECONDS;
